# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-14 14:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import mezzanine.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_auto_20150527_1555'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('english_name', models.CharField(max_length=30, null=True, unique=True, verbose_name='英文姓名')),
                ('chinese_name', models.CharField(max_length=40, null=True, verbose_name='中文姓名')),
                ('country', models.CharField(max_length=40, null=True, verbose_name='国家')),
                ('description', models.TextField(null=True, verbose_name='作者简介')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('blogpost_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BlogPost')),
                ('chinese_title', models.CharField(max_length=100, null=True, verbose_name='中文书名')),
                ('isbn', models.CharField(max_length=100, null=True, verbose_name='ISBN')),
                ('publication_date', models.DateField(null=True, verbose_name='出版日期')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Author', verbose_name='作者')),
            ],
            options={
                'verbose_name': '图书',
                'verbose_name_plural': '图书',
            },
            bases=('blog.blogpost',),
        ),
        migrations.CreateModel(
            name='BookCategory',
            fields=[
                ('blogcategory_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='blog.BlogCategory')),
                ('image', models.ImageField(null=True, upload_to='categories', verbose_name='图片')),
            ],
            options={
                'verbose_name': '书籍分类',
                'verbose_name_plural': '书籍分类',
            },
            bases=('blog.blogcategory',),
        ),
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField(db_index=True)),
                ('title', models.CharField(max_length=100, null=True, verbose_name='章节标题')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('audio_file', models.FileField(blank=True, help_text='Allowed type - .mp3, .wav, .ogg', upload_to='audio_file', verbose_name='音频文件')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.Book', verbose_name='所属书籍')),
            ],
            options={
                'verbose_name': '章节管理',
                'verbose_name_plural': '章节管理',
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='名称')),
                ('website', models.URLField(verbose_name='网址')),
            ],
            options={
                'verbose_name': '出版社',
                'verbose_name_plural': '出版社',
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, upload_to='avatar')),
                ('bio', models.TextField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '会员管理',
                'verbose_name_plural': '会员管理',
            },
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.Publisher', verbose_name='出版社'),
        ),
    ]
