# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-10-15 02:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.FileField(null=True, upload_to='covers', verbose_name='图片'),
        ),
    ]
